import path from 'node:path';
import { fileURLToPath } from 'node:url';

import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Glob patterns must use forward slashes even on Windows, where path.resolve()
// returns backslash-separated paths that tinyglobby (vitest's glob matcher)
// can't match against `**` patterns. Harmless on Linux (forward slashes already).
const toPosix = (p: string) => p.split(path.sep).join('/');

// `virtual:vpt-features` is generated by the vpt-features plugin in frontend/vite.config.ts
// (docs/technical/FEATURES.md). Component tests exercise core pages only, so the module is
// stubbed as "no optional features" here — without it every import of src/config/features.ts
// (App, Dashboard, navItems…) fails to resolve under vitest.
const vptFeaturesStub = {
  name: 'vpt-features-stub',
  resolveId(id: string) {
    return id === 'virtual:vpt-features' ? '\0virtual:vpt-features' : null;
  },
  load(id: string) {
    return id === '\0virtual:vpt-features' ? 'export const features = [];' : null;
  },
};

// frontend/vite.config.ts's vptFeaturesPlugin resolves bare imports (react, @mui/...) from
// files under features/*/frontend/ as if imported from frontend/src, since features/ sits
// outside frontend/ and can't see frontend/node_modules by walking up. Component tests hit
// this the first time a features/ page was tested directly (features/cicd/frontend/CICDReportsPage.tsx
// importing @mui/icons-material) — replicate the same resolution here rather than mocking
// every third-party import a feature page happens to use.
const featuresDir = toPosix(path.resolve(__dirname, '../../features'));
const frontendEntry = path.resolve(__dirname, '../../frontend/src/main.tsx');
const resolveFeatureBareImports = {
  name: 'resolve-feature-bare-imports',
  async resolveId(this: any, source: string, importer: string | undefined, options: unknown) {
    if (
      importer &&
      toPosix(importer).startsWith(featuresDir) &&
      !source.startsWith('.') &&
      !source.startsWith('/') &&
      !source.startsWith('\0')
    ) {
      return this.resolve(source, frontendEntry, { ...(options as object), skipSelf: true });
    }
    return null;
  },
};

export default defineConfig({
  plugins: [react(), vptFeaturesStub, resolveFeatureBareImports],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, '../../frontend/src'),
    },
  },
  // Vitest runs with frontend/ as root, and Vite refuses to serve files outside it. A test
  // file that lives beside the feature code it covers (features/<name>/**/*.test.ts) is
  // outside that root, so without this it fails to load with "Does the file exist?" even
  // though it does. Importing a feature file from tests/frontend/ was never affected, which
  // is why this only shows up once tests live under features/.
  server: { fs: { allow: [path.resolve(__dirname, '../..')] } },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: [path.resolve(__dirname, './setup.ts')],
    // Page/component tests live here; a feature's *pure logic* tests live beside the code
    // they cover (features/<name>/**/*.test.ts), per docs/technical/FEATURES.md → "Testing a
    // feature". Both are picked up by the same `frontend-component-tests` CI job — without the
    // features/ glob a test written where that doc says to put it would silently never run.
    include: [
      toPosix(path.resolve(__dirname, './**/*.test.ts')),
      toPosix(path.resolve(__dirname, './**/*.test.tsx')),
      toPosix(path.resolve(__dirname, '../../features/*/**/*.test.ts')),
      toPosix(path.resolve(__dirname, '../../features/*/**/*.test.tsx')),
    ],
    exclude: ['**/node_modules/**'],
    clearMocks: true,
    restoreMocks: true,
    // Unit tests must be fast — a hook mock that returns a fresh object/function
    // literal per render can create an infinite re-render loop with no error and
    // no natural end (hit this exact bug backfilling tests on 2026-09-06). This
    // caps that failure mode to a loud timeout instead of a silent multi-minute hang.
    testTimeout: 10000,
  },
});
