-- TASK-10 env2 parity ROLLBACK: restore the pre-migration open state exactly.
-- Generated 2026-09-08 from the same live snapshot as the migration.

BEGIN;

GRANT ALL ON public."active_incidents_summary" TO anon;
GRANT ALL ON public."agent_benchmark_results" TO anon;
GRANT ALL ON public."agent_benchmark_runs" TO anon;
GRANT ALL ON public."agent_benchmarks" TO anon;
GRANT ALL ON public."agent_event_triggers" TO anon;
GRANT ALL ON public."agent_execution_history" TO anon;
GRANT ALL ON public."agent_feedback" TO anon;
GRANT ALL ON public."agent_instances" TO anon;
GRANT ALL ON public."agent_leaderboard" TO anon;
GRANT ALL ON public."agent_metrics" TO anon;
GRANT ALL ON public."agent_registry" TO anon;
GRANT ALL ON public."agent_scores" TO anon;
GRANT ALL ON public."ai_analysis_cache" TO anon;
GRANT ALL ON public."ai_graph_cache" TO anon;
GRANT ALL ON public."ai_prompt_disambiguation" TO anon;
GRANT ALL ON public."alerts" TO anon;
GRANT ALL ON public."campaign_executions" TO anon;
GRANT ALL ON public."campaigns" TO anon;
GRANT ALL ON public."campaigns_history" TO anon;
GRANT ALL ON public."deployment_executions" TO anon;
GRANT ALL ON public."deployments" TO anon;
GRANT ALL ON public."device" TO anon;
GRANT ALL ON public."device_availability_summary" TO anon;
GRANT ALL ON public."device_flags" TO anon;
GRANT ALL ON public."device_models" TO anon;
GRANT ALL ON public."edge_metrics" TO anon;
GRANT ALL ON public."environment_profiles" TO anon;
GRANT ALL ON public."event_log" TO anon;
GRANT ALL ON public."executable_tags" TO anon;
GRANT ALL ON public."execution_results" TO anon;
GRANT ALL ON public."folders" TO anon;
GRANT ALL ON public."heatmaps" TO anon;
GRANT ALL ON public."library_visibility" TO anon;
GRANT ALL ON public."navigation_edges" TO anon;
GRANT ALL ON public."navigation_nodes" TO anon;
GRANT ALL ON public."navigation_trees" TO anon;
GRANT ALL ON public."navigation_trees_history" TO anon;
GRANT ALL ON public."node_metrics" TO anon;
GRANT ALL ON public."profiles" TO anon;
GRANT ALL ON public."requirements" TO anon;
GRANT ALL ON public."requirements_coverage_summary" TO anon;
GRANT ALL ON public."resource_lock_queue" TO anon;
GRANT ALL ON public."resource_locks" TO anon;
GRANT ALL ON public."scheduled_events" TO anon;
GRANT ALL ON public."script_requirements" TO anon;
GRANT ALL ON public."script_results" TO anon;
GRANT ALL ON public."scripts" TO anon;
GRANT ALL ON public."system_device_metrics" TO anon;
GRANT ALL ON public."system_incident" TO anon;
GRANT ALL ON public."system_metrics" TO anon;
GRANT ALL ON public."tags" TO anon;
GRANT ALL ON public."team_members" TO anon;
GRANT ALL ON public."teams" TO anon;
GRANT ALL ON public."test_cases" TO anon;
GRANT ALL ON public."test_executions" TO anon;
GRANT ALL ON public."test_results" TO anon;
GRANT ALL ON public."testcase_definitions" TO anon;
GRANT ALL ON public."testcase_definitions_history" TO anon;
GRANT ALL ON public."testcase_requirements" TO anon;
GRANT ALL ON public."uncovered_requirements" TO anon;
GRANT ALL ON public."userinterfaces" TO anon;
GRANT ALL ON public."verifications_references" TO anon;
GRANT ALL ON public."workspace_members" TO anon;
GRANT ALL ON public."workspaces" TO anon;
GRANT ALL ON public."zap_results" TO anon;

GRANT ALL ON public."active_incidents_summary" TO authenticated;
GRANT ALL ON public."agent_benchmark_results" TO authenticated;
GRANT ALL ON public."agent_benchmark_runs" TO authenticated;
GRANT ALL ON public."agent_benchmarks" TO authenticated;
GRANT ALL ON public."agent_event_triggers" TO authenticated;
GRANT ALL ON public."agent_execution_history" TO authenticated;
GRANT ALL ON public."agent_feedback" TO authenticated;
GRANT ALL ON public."agent_instances" TO authenticated;
GRANT ALL ON public."agent_leaderboard" TO authenticated;
GRANT ALL ON public."agent_metrics" TO authenticated;
GRANT ALL ON public."agent_registry" TO authenticated;
GRANT ALL ON public."agent_scores" TO authenticated;
GRANT ALL ON public."ai_analysis_cache" TO authenticated;
GRANT ALL ON public."ai_graph_cache" TO authenticated;
GRANT ALL ON public."ai_prompt_disambiguation" TO authenticated;
GRANT ALL ON public."alerts" TO authenticated;
GRANT ALL ON public."campaign_executions" TO authenticated;
GRANT ALL ON public."campaigns" TO authenticated;
GRANT ALL ON public."campaigns_history" TO authenticated;
GRANT ALL ON public."deployment_executions" TO authenticated;
GRANT ALL ON public."deployments" TO authenticated;
GRANT ALL ON public."device" TO authenticated;
GRANT ALL ON public."device_availability_summary" TO authenticated;
GRANT ALL ON public."device_flags" TO authenticated;
GRANT ALL ON public."device_models" TO authenticated;
GRANT ALL ON public."edge_metrics" TO authenticated;
GRANT ALL ON public."environment_profiles" TO authenticated;
GRANT ALL ON public."event_log" TO authenticated;
GRANT ALL ON public."executable_tags" TO authenticated;
GRANT ALL ON public."execution_results" TO authenticated;
GRANT ALL ON public."folders" TO authenticated;
GRANT ALL ON public."heatmaps" TO authenticated;
GRANT ALL ON public."library_visibility" TO authenticated;
GRANT ALL ON public."navigation_edges" TO authenticated;
GRANT ALL ON public."navigation_nodes" TO authenticated;
GRANT ALL ON public."navigation_trees" TO authenticated;
GRANT ALL ON public."navigation_trees_history" TO authenticated;
GRANT ALL ON public."node_metrics" TO authenticated;
GRANT ALL ON public."requirements" TO authenticated;
GRANT ALL ON public."requirements_coverage_summary" TO authenticated;
GRANT ALL ON public."resource_lock_queue" TO authenticated;
GRANT ALL ON public."resource_locks" TO authenticated;
GRANT ALL ON public."scheduled_events" TO authenticated;
GRANT ALL ON public."script_requirements" TO authenticated;
GRANT ALL ON public."script_results" TO authenticated;
GRANT ALL ON public."scripts" TO authenticated;
GRANT ALL ON public."system_device_metrics" TO authenticated;
GRANT ALL ON public."system_incident" TO authenticated;
GRANT ALL ON public."system_metrics" TO authenticated;
GRANT ALL ON public."tags" TO authenticated;
GRANT ALL ON public."teams" TO authenticated;
GRANT ALL ON public."test_cases" TO authenticated;
GRANT ALL ON public."test_executions" TO authenticated;
GRANT ALL ON public."test_results" TO authenticated;
GRANT ALL ON public."testcase_definitions" TO authenticated;
GRANT ALL ON public."testcase_definitions_history" TO authenticated;
GRANT ALL ON public."testcase_requirements" TO authenticated;
GRANT ALL ON public."uncovered_requirements" TO authenticated;
GRANT ALL ON public."userinterfaces" TO authenticated;
GRANT ALL ON public."verifications_references" TO authenticated;
GRANT ALL ON public."workspace_members" TO authenticated;
GRANT ALL ON public."workspaces" TO authenticated;
GRANT ALL ON public."zap_results" TO authenticated;

GRANT SELECT ON public."mv_full_navigation_trees" TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated;

-- Recreate the dropped tautology policies verbatim.
CREATE POLICY "agent_benchmark_results_access_policy" ON public."agent_benchmark_results" AS PERMISSIVE FOR ALL TO authenticated USING (((( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_benchmark_results" ON public."agent_benchmark_results" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_benchmark_runs_access_policy" ON public."agent_benchmark_runs" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_benchmark_runs" ON public."agent_benchmark_runs" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_benchmarks_access_policy" ON public."agent_benchmarks" AS PERMISSIVE FOR ALL TO authenticated USING (((( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_benchmarks" ON public."agent_benchmarks" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_event_triggers_access_policy" ON public."agent_event_triggers" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_event_triggers" ON public."agent_event_triggers" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_execution_history_access_policy" ON public."agent_execution_history" AS PERMISSIVE FOR SELECT TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_execution_history" ON public."agent_execution_history" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_feedback_access_policy" ON public."agent_feedback" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_feedback" ON public."agent_feedback" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_instances_access_policy" ON public."agent_instances" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_instances" ON public."agent_instances" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_registry_access_policy" ON public."agent_registry" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_registry" ON public."agent_registry" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "agent_scores_access_policy" ON public."agent_scores" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_agent_scores" ON public."agent_scores" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "ai_analysis_cache_access_policy" ON public."ai_analysis_cache" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "ai_graph_cache_access_policy" ON public."ai_graph_cache" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "ai_prompt_disambiguation_access_policy" ON public."ai_prompt_disambiguation" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "alerts_access_policy" ON public."alerts" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "campaign_executions_access_policy" ON public."campaign_executions" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "campaigns_access_policy" ON public."campaigns" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_campaigns" ON public."campaigns" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "campaigns_history_access_policy" ON public."campaigns_history" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_campaigns_history" ON public."campaigns_history" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "deployment_executions_access_policy" ON public."deployment_executions" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "deployments_access_policy" ON public."deployments" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "device_access_policy" ON public."device" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "device_flags_access_policy" ON public."device_flags" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "device_models_access_policy" ON public."device_models" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "edge_metrics_access_policy" ON public."edge_metrics" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "environment_profiles_access_policy" ON public."environment_profiles" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "event_log_access_policy" ON public."event_log" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_event_log" ON public."event_log" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "executable_tags_access_policy" ON public."executable_tags" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "service_role_all_executable_tags" ON public."executable_tags" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "execution_results_access_policy" ON public."execution_results" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "folders_access_policy" ON public."folders" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "service_role_all_folders" ON public."folders" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "heatmaps_access_policy" ON public."heatmaps" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "library_visibility_access_policy" ON public."library_visibility" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_library_visibility" ON public."library_visibility" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "navigation_edges_access_policy" ON public."navigation_edges" AS PERMISSIVE FOR ALL TO public USING (((team_id IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::uuid[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "navigation_nodes_access_policy" ON public."navigation_nodes" AS PERMISSIVE FOR ALL TO public USING (((team_id IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::uuid[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "navigation_trees_access_policy" ON public."navigation_trees" AS PERMISSIVE FOR ALL TO public USING (((team_id IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::uuid[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "navigation_trees_history_access_policy" ON public."navigation_trees_history" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "node_metrics_access_policy" ON public."node_metrics" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "requirements_access_policy" ON public."requirements" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_requirements" ON public."requirements" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "resource_lock_queue_access_policy" ON public."resource_lock_queue" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_resource_lock_queue" ON public."resource_lock_queue" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "resource_locks_access_policy" ON public."resource_locks" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_resource_locks" ON public."resource_locks" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "scheduled_events_access_policy" ON public."scheduled_events" AS PERMISSIVE FOR ALL TO authenticated USING ((((team_id)::text IN ( SELECT unnest((COALESCE((((current_setting('request.jwt.claims'::text, true))::json ->> 'team_ids'::text))::text[], ARRAY[]::text[]))::character varying[]) AS unnest)) OR (( SELECT role() AS role) = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_scheduled_events" ON public."scheduled_events" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "script_requirements_access_policy" ON public."script_requirements" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_script_requirements" ON public."script_requirements" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "script_results_access_policy" ON public."script_results" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "scripts_access_policy" ON public."scripts" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "service_role_all_scripts" ON public."scripts" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "system_device_metrics_access_policy" ON public."system_device_metrics" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "system_incident_access_policy" ON public."system_incident" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "system_metrics_access_policy" ON public."system_metrics" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "service_role_all_tags" ON public."tags" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "tags_access_policy" ON public."tags" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "teams_access_policy" ON public."teams" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "test_cases_access_policy" ON public."test_cases" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "test_executions_access_policy" ON public."test_executions" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "test_results_access_policy" ON public."test_results" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_testcase_definitions" ON public."testcase_definitions" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "testcase_definitions_access_policy" ON public."testcase_definitions" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_testcase_history" ON public."testcase_definitions_history" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "testcase_history_access_policy" ON public."testcase_definitions_history" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "service_role_all_testcase_requirements" ON public."testcase_requirements" AS PERMISSIVE FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY "testcase_requirements_access_policy" ON public."testcase_requirements" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "userinterfaces_open_access" ON public."userinterfaces" AS PERMISSIVE FOR ALL TO public USING (true);
CREATE POLICY "verifications_references_access_policy" ON public."verifications_references" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "workspace_members_access_policy" ON public."workspace_members" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "workspaces_access_policy" ON public."workspaces" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));
CREATE POLICY "zap_results_access_policy" ON public."zap_results" AS PERMISSIVE FOR ALL TO public USING (((uid() IS NULL) OR (role() = 'service_role'::text) OR true));

COMMIT;
