-- ============================================================================
-- DEVICE CONTROL SESSIONS TABLE
-- Durable history of device lock sessions (manual control + script/deployment
-- executions). The server's in-memory DeviceLockManager is authoritative for
-- live locking; this table is a best-effort audit trail written asynchronously
-- so Grafana can compute device occupancy (manual + scripted) over time.
-- One row per lock session: started_at set on acquire, ended_at on release.
-- ============================================================================

CREATE TABLE device_control_sessions (
    id UUID PRIMARY KEY,                       -- generated by the server (lock manager)
    host_name VARCHAR(255) NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    owner_type VARCHAR(50) NOT NULL,           -- 'manual_control', 'script_execution', 'deployment_execution', ...
    owner_session_id VARCHAR(255),
    owner_user_id VARCHAR(255),
    owner_job_id VARCHAR(255),
    lock_reason TEXT,
    locked_ip VARCHAR(64),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,  -- refreshed by heartbeats; = started_at for script locks (they never heartbeat)
    ended_at TIMESTAMP WITH TIME ZONE,               -- NULL while session is open
    end_reason VARCHAR(50),                          -- 'released','superseded','takeover','expired','force_unlock','host_restart','dangling','stale_sweep'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_dcs_device_time ON device_control_sessions(host_name, device_id, started_at DESC);
CREATE INDEX idx_dcs_started ON device_control_sessions(started_at);
CREATE INDEX idx_dcs_open ON device_control_sessions(host_name, device_id) WHERE ended_at IS NULL;
CREATE INDEX idx_dcs_owner_type ON device_control_sessions(owner_type);

COMMENT ON TABLE device_control_sessions IS 'History of device lock sessions (manual + execution) for occupancy analytics; written best-effort by backend_server lock manager';
COMMENT ON COLUMN device_control_sessions.last_seen_at IS 'Last heartbeat/refresh; used as end bound when a session is closed as dangling/stale';
COMMENT ON COLUMN device_control_sessions.ended_at IS 'NULL while lock is held; set when lock is released by any path';
COMMENT ON COLUMN device_control_sessions.end_reason IS 'released|superseded|takeover|expired|force_unlock|host_restart|dangling|stale_sweep';

-- Row Level Security: platform default (RLS on, open policy; authz lives in the server layer)
ALTER TABLE device_control_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "device_control_sessions_access_policy" ON device_control_sessions
FOR ALL TO public USING (true);
