#!/usr/bin/env python3
"""Rebuild the bug index from the bug files.

The index was maintained by hand — add a row, then edit Status and Fixed in here AND in the file
when it ships — so it drifted in ways nobody could see: two files sharing a number, a description
containing a raw `|` that shifted every column after it, titles that were whole paragraphs
because the column was filled with the write-up.

Now it is generated. Each bug's one-line title comes from its own H1 and its state from its own
meta table, so the index cannot disagree with the files. Bugs are grouped by the build that
carries them, newest first, in the same bullet grammar the release note uses — which is what lets
one component render both pages.

The curated one-paragraph descriptions in the previous index are preserved: they are better than
anything derivable, so they are read back from the table this replaces.
"""
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
BUGS = os.path.join(REPO, 'docs', 'bugs')
INDEX = os.path.join(BUGS, 'README.md')
NOTE = os.path.join(REPO, 'docs', 'release_note', 'README.md')
MARKER = '<!-- generated by scripts/docs/build_bug_index.py — do not edit below -->'


def meta(text: str, field: str) -> str:
    m = re.search(rf'^\|\s*{field}\s*\|(.+?)\|\s*$', text, re.M)
    return m.group(1).strip() if m else ''


def build_dates() -> dict:
    """{build number: date} from the release note's own headings."""
    out = {}
    if os.path.exists(NOTE):
        for m in re.finditer(r'^## build (\d+) — (\S+)', open(NOTE, encoding='utf-8').read(), re.M):
            out[m.group(1)] = m.group(2)
    return out


def note_builds() -> dict:
    """{BUG-nnnn: build} from which release-note section cites the bug's file.

    The release note is the artifact that is actually cut, reviewed and shipped, so it — not a
    field typed by hand weeks earlier — is what a fix's build means. Two failures made that the
    rule rather than a preference:

      * `Fixed in` was filled from VERSION.txt at writing time. That counter bumps on every
        commit and every branch carries its own series, so it never names a release: BUG-0122
        came back with `build 9062`, which was a worktree's counter, and no such build ever
        existed on main. The release build is knowable only at cut time, which is exactly when
        the note heading is written.
      * Nothing made the two pages agree. BUG-0087/0089/0091 sat under `## build 8887` in the
        note and under Unreleased in this index for two releases, and BUG-0067/0068 claimed
        `build 8713` in files whose commits landed after that tag.

    A bug cited by several sections belongs to the earliest one that carried it.
    """
    out = {}
    if not os.path.exists(NOTE):
        return out
    section = None
    for line in open(NOTE, encoding='utf-8'):
        h = re.match(r'^##\s+(.+?)\s*$', line)
        if h:
            m = re.match(r'build\s+(\d+)', h.group(1).strip())
            section = m.group(1) if m else None
            continue
        if section is None or not line.lstrip().startswith(('-', '`', '[')) and '[BUG-' not in line:
            continue
        for bug_id in re.findall(r'\[(BUG-\d+)\]\(\.\./bugs/', line):
            prev_build = out.get(bug_id)
            if prev_build is None or int(section) < int(prev_build):
                out[bug_id] = section
    return out


def from_old_index() -> dict:
    """{BUG-nnnn: {desc, fixed_in}} from the index being replaced.

    Both are worth keeping. The descriptions are hand-written and better than anything derivable.
    The `Fixed in` column is the one that was actually maintained at ship time — the files' own
    `Fixed in` still says "Unreleased" for 42 bugs the index correctly places in build 8713, so
    the table is the authority on which build carries a fix and the file is the authority on what
    the fix was.
    """
    out = {}
    if not os.path.exists(INDEX):
        return out
    group = ''
    for line in open(INDEX, encoding='utf-8'):
        # --- the generated form, so a second run does not lose what the first one placed ---
        h = re.match(r'^##\s+(.+?)\s*$', line)
        if h:
            g = h.group(1)
            group = '' if g.lower().startswith('unreleased') else g.split('—')[0].strip()
            continue
        b = re.match(r'^-\s+\*\*(.+?)\*\*\s*(.*)$', line)
        if b and '[BUG-' in b.group(2):
            bid = re.search(r'\[(BUG-\d+)\]', b.group(2)).group(1)
            # `— desc · reported … · [BUG-nnnn](f)` or, with no description, `· reported … · [BUG…]`
            desc = re.split(r'·\s*(?:reported\b|\[BUG-)', b.group(2))[0]
            desc = re.sub(r'^[—-]\s*', '', desc.strip()).strip()
            out[bid] = {'desc': desc, 'fixed_in': group}
            continue
        # --- the original hand-written table ---
        m = re.match(r'^\|\s*\[(BUG-\d+)\]\([^)]*\)\s*\|([^|]*)\|(.*)$', line)
        if not m:
            continue
        # ` desc | Status | Fixed in | Commit |` -> 5 parts, the last empty
        cells = m.group(3).rsplit('|', 4)
        ok = len(cells) == 5
        out[m.group(1)] = {
            'desc': cells[0].strip() if ok else m.group(3).strip(),
            'fixed_in': cells[2].strip() if ok else '',
        }
    return out


def main() -> int:
    dates = build_dates()
    cited = note_builds()
    prev = from_old_index()
    bugs = []
    for fn in sorted(os.listdir(BUGS)):
        if not (fn.startswith('BUG-') and fn.endswith('.md')):
            continue
        text = open(os.path.join(BUGS, fn), encoding='utf-8').read()
        h1 = re.search(r'^#\s*(BUG-\d+)\s*[—-]\s*(.+)$', text, re.M)
        if not h1:
            print(f'skip (no H1 title): {fn}', file=sys.stderr)
            continue
        bug_id, title = h1.group(1), h1.group(2).strip()
        old = prev.get(bug_id, {})
        # The note first: it is the shipped record, and a hand-typed build number has been
        # wrong often enough (see note_builds) that it cannot outrank it. Falling back to the
        # old index keeps the builds it correctly placed for bugs the note never cited.
        group = cited.get(bug_id)
        if group is None:
            fixed_in = old.get('fixed_in') or meta(text, 'Fixed in')
            b = re.search(r'build\s*(\d+)', fixed_in)
            group = b.group(1) if b else None
        bugs.append({
            'id': bug_id, 'file': fn, 'title': title, 'group': group,
            'reported': meta(text, 'Reported').split('(')[0].strip(),
            'desc': old.get('desc', ''),
        })

    # newest build first, then unreleased on top of everything
    groups: dict = {}
    for b in bugs:
        groups.setdefault(b['group'], []).append(b)
    order = [None] + sorted((g for g in groups if g), key=int, reverse=True)

    L = []
    for g in order:
        rows = groups.get(g)
        if not rows:
            continue
        rows.sort(key=lambda r: r['id'], reverse=True)
        head = 'Unreleased' if g is None else f'build {g}' + (f' — {dates[g]}' if g in dates else '')
        L.append(f'## {head}')
        L.append('')
        for r in rows:
            line = f"- **{r['title']}** — {r['desc']}" if r['desc'] else f"- **{r['title']}**"
            line += f" · reported {r['reported']}" if r['reported'] else ''
            line += f" · [{r['id']}]({r['file']})"
            L.append(line)
        L.append('')

    # Everything below the marker is ours to rewrite; everything above it is the page's header,
    # which stays hand-written. An explicit marker rather than "the first ## heading", so the
    # header can grow without the generator eating it.
    text = open(INDEX, encoding='utf-8').read()
    if MARKER in text:
        head = text[:text.index(MARKER)]
    elif '## Index' in text:
        head = text[:text.index('## Index')]          # the original hand-written page
    else:
        head = text.split('\n## ')[0] + '\n\n'
    open(INDEX, 'w', encoding='utf-8').write(head + MARKER + '\n\n' + '\n'.join(L).rstrip() + '\n')
    print(f'{len(bugs)} bugs in {len([g for g in order if groups.get(g)])} groups')
    return 0


if __name__ == '__main__':
    sys.exit(main())
