"""
Security reports routes.

Serves the Bandit/Snyk/npm-audit scan output generated by
scripts/generate-security-docs.sh (docs/security/). This content used to be
published as public static files under /docs/security/ on the frontend site;
it now requires an authenticated admin session, since file paths and finding
detail are useful recon for an attacker and shouldn't be reachable by an
anonymous visitor.
"""

import os

from flask import Blueprint, Response, jsonify

from backend_server.src.lib.auth_middleware import require_user_auth, require_role
from backend_server.src.lib.utils.route_handlers import handle_route_exceptions

server_security_bp = Blueprint('server_security', __name__, url_prefix='/server/security')

# docs/security/, resolved relative to this file so it works both from a local
# checkout and from the deployed repo root (/opt/virtualpytest).
_ROUTES_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_ROUTES_DIR, '..', '..', '..'))
_SECURITY_DOCS_DIR = os.path.join(_REPO_ROOT, 'docs', 'security')

# Exact basenames only — never build a path from user input directly, to rule out traversal.
_ALLOWED_REPORTS = {
    'host-report',
    'server-report',
    'frontend-report',
    'shared-report',
    'snyk-host-report',
    'snyk-server-report',
    'snyk-shared-report',
}


@server_security_bp.route('/dashboard', methods=['GET'])
@require_user_auth
@require_role('admin')
@handle_route_exceptions('server_security:dashboard')
def get_security_dashboard():
    """Return the pre-rendered Bandit/Snyk/npm-audit HTML dashboard."""
    path = os.path.join(_SECURITY_DOCS_DIR, 'index.html')
    if not os.path.isfile(path):
        return jsonify({'success': False, 'error': 'Security dashboard not generated yet'}), 404
    with open(path, 'r', encoding='utf-8') as f:
        html = f.read()
    return Response(html, mimetype='text/html')


@server_security_bp.route('/reports/<report_name>', methods=['GET'])
@require_user_auth
@require_role('admin')
@handle_route_exceptions('server_security:report')
def get_security_report(report_name: str):
    """Return one raw scan report as JSON (the dashboard's 'JSON ↗' links)."""
    if report_name not in _ALLOWED_REPORTS:
        return jsonify({'success': False, 'error': 'Unknown report'}), 404
    path = os.path.join(_SECURITY_DOCS_DIR, f'{report_name}.json')
    if not os.path.isfile(path):
        return jsonify({'success': False, 'error': 'Report not generated yet'}), 404
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    return Response(content, mimetype='application/json')
