#!/bin/bash
#
# install_bt_pinning.sh — pin USB Bluetooth dongles to deterministic hci indices.
#
# Run ONCE per robot/host:
#   sudo bash /opt/virtualpytest/setup/proxmox/vm/backend-host/install_bt_pinning.sh
#
# WHY:
#   hciN numbering is handed out by the btusb driver in probe order at boot.
#   With several IDENTICAL Belkin dongles (050d:065a) the order — and therefore
#   which dongle is hci1 vs hci2 vs ... — can flip on every reboot/replug.
#   There is NO udev NAME= for the bluetooth subsystem, and the kernel allocates
#   hci indices densely from the lowest free number, so you cannot force an
#   arbitrary index. The only stable identity is the physical USB PORT PATH.
#
# CONVENTION (identical on every robot):
#   * onboard / non-Belkin radio  -> hci0
#   * Belkin STB dongles          -> hci1, hci2, ... in ASCENDING USB-port order
#   So cable each STB so that the lowest USB port == the lowest device number,
#   and DEVICE{N}_BLE_ADAPTER_HCI in .env stays uniform across the fleet.
#   On a fully-populated 4-dongle hub (ports 5-1..5-4) this yields exactly
#   5-1->hci1 ... 5-4->hci4. With gaps below, the kernel collapses to a dense
#   sequence (hci1, hci2, ...) — it cannot leave holes.
#
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: run as root (sudo)." >&2
  exit 1
fi

RUNTIME=/usr/local/sbin/pin-bt-adapters.sh
UNIT=/etc/systemd/system/pin-bt-adapters.service

# Belkin BCM20702A1 BT 4.0 dongle. Override at install time if your fleet uses
# a different USB BT dongle, e.g.  BELKIN_VID=0a12 BELKIN_PID=0001 sudo bash ...
BELKIN_VID="${BELKIN_VID:-050d}"
BELKIN_PID="${BELKIN_PID:-065a}"

echo "[install_bt_pinning] writing $RUNTIME (dongle ${BELKIN_VID}:${BELKIN_PID})"
cat > "$RUNTIME" <<EOF
#!/bin/bash
# AUTO-GENERATED by install_bt_pinning.sh — do not edit by hand.
# Pin USB Bluetooth dongles to deterministic hci indices.
# onboard/non-dongle radios -> hci0+, then ${BELKIN_VID}:${BELKIN_PID} dongles
# bound in ascending USB-port order so the lowest port gets the lowest hci.
set -u
DRV=/sys/bus/usb/drivers/btusb
DONGLE_VID="${BELKIN_VID}"
DONGLE_PID="${BELKIN_PID}"

onboard=()
dongle=()

# Classify every currently-present btusb HCI interface (:1.0 is the one that
# creates the hciN device; :1.1/:1.2 are the SCO/audio interfaces we don't use).
for d in "\$DRV"/*:1.0; do
  [ -e "\$d" ] || continue
  iface=\$(basename "\$d")          # e.g. 5-4:1.0
  dev=\${iface%%:*}                 # e.g. 5-4
  vid=\$(cat "/sys/bus/usb/devices/\$dev/idVendor" 2>/dev/null || true)
  pid=\$(cat "/sys/bus/usb/devices/\$dev/idProduct" 2>/dev/null || true)
  if [ "\$vid" = "\$DONGLE_VID" ] && [ "\$pid" = "\$DONGLE_PID" ]; then
    dongle+=("\$iface")
  else
    onboard+=("\$iface")
  fi
done

# Detach every btusb interface so the index allocator starts clean.
for d in "\$DRV"/*:*; do
  [ -e "\$d/driver" ] && echo "\$(basename "\$d")" > "\$DRV/unbind" 2>/dev/null || true
done
sleep 1

# Bind one interface and WAIT until its OWN hci device registers before
# returning — a fixed sleep is not enough. The onboard MediaTek combo chip
# (0e8d:c616) downloads firmware on bind and can take several seconds to call
# hci_register_dev; with the old `sleep 1` the fast Belkin dongles claimed
# hci0/hci1 while the MediaTek was still probing, so it landed on hci2 instead
# of hci0 and the dongles came out off-by-one. Polling for the just-bound
# device's own hciN closes that race. See BLUETOOTH.md §6.7.25-followup.
bind_one() {
  local iface="\$1" dev="\${1%%:*}" _i h
  echo "\$iface" > "\$DRV/bind" 2>/dev/null || true
  for _i in \$(seq 1 60); do
    for h in /sys/class/bluetooth/hci*; do
      [ -e "\$h" ] || continue
      case "\$(readlink -f "\$h")" in */\$dev/*) return 0 ;; esac
    done
    sleep 0.25
  done
}

echo "pin-bt: onboard=[\${onboard[*]:-}] dongles=[\${dongle[*]:-}]"
# Onboard radios first -> claim hci0 (and up, if more than one).
for i in "\${onboard[@]:-}"; do [ -n "\$i" ] && bind_one "\$i"; done
# Dongles in ascending USB-port order -> hci1, hci2, ...
while read -r i; do [ -n "\$i" ] && bind_one "\$i"; done \
  < <(printf '%s\n' "\${dongle[@]:-}" | sort -V)

# Log the resulting map for journalctl -u pin-bt-adapters
for h in /sys/class/bluetooth/hci*; do
  [ -e "\$h" ] || continue
  n=\$(basename "\$h")
  p=\$(readlink -f "\$h" | grep -oE 'usb[0-9]+/[0-9.-]+/[0-9.-]+' | tail -1)
  mac=\$(hciconfig "\$n" 2>/dev/null | grep -oE '([0-9A-F]{2}:){5}[0-9A-F]{2}' | head -1)
  echo "pinned \$n  port=\$p  mac=\$mac"
done
EOF
chmod +x "$RUNTIME"

echo "[install_bt_pinning] writing $UNIT"
cat > "$UNIT" <<EOF
[Unit]
Description=Pin USB Bluetooth dongles to deterministic hci indices
After=bluetooth.service
Before=vpt-host.service
Wants=bluetooth.service

[Service]
Type=oneshot
ExecStart=$RUNTIME
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

echo "[install_bt_pinning] enabling + running"
systemctl daemon-reload
systemctl enable --now pin-bt-adapters.service

echo
echo "[install_bt_pinning] resulting adapter map:"
for h in /sys/class/bluetooth/hci*; do
  [ -e "$h" ] || continue
  n=$(basename "$h")
  p=$(readlink -f "$h" | grep -oE 'usb[0-9]+/[0-9.-]+/[0-9.-]+' | tail -1)
  mac=$(hciconfig "$n" 2>/dev/null | grep -oE '([0-9A-F]{2}:){5}[0-9A-F]{2}' | head -1)
  echo "  $n  port=$p  mac=$mac"
done
echo
echo "[install_bt_pinning] done. Reboot once and re-check the map above to confirm it holds."
