#!/bin/bash

# Script to copy only necessary documentation files to frontend/public/docs
echo "Starting copy-docs script..."
set +e  # Don't exit on errors for now
# - OpenAPI HTML docs (original)
# - Only markdown files that are actually referenced/linked

set -e

# Debug info
echo "Current working directory: $(pwd)"
echo "Script location: $0"

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}Copying documentation files...${NC}"

# Check if docs directory exists
if [ ! -d "../docs" ]; then
  echo "Warning: ../docs directory not found. Skipping documentation copy."
  exit 0
fi

# Build into a staging directory and swap it in only once everything is copied.
#
# This used to `rm -rf public/docs` up front and copy into it in place. prebuild.sh runs
# this script under `timeout -k 5` (see DOC_TIMEOUT), so being killed part-way left the
# site with a half-populated public/docs — which is what took every /docs/* page on
# virtualpytest.angelstreet.io down to "Error Loading Documentation" (BUG-0060): only
# docs/api survived, the markdown and docs-manifest.json never got copied, and the
# already-good previous copy had been deleted. Staging + a final swap makes a timeout,
# a `set -e` abort or a missing source leave the PREVIOUS docs serving instead.
DOCS_FINAL="public/docs"
DOCS_OUT="public/.docs-build.$$"
export DOCS_OUT

cleanup_staging() {
    rm -rf "$DOCS_OUT" 2>/dev/null || true
}
trap cleanup_staging EXIT INT TERM

echo -e "${YELLOW}→${NC} Staging docs in $DOCS_OUT ..."
if ! rm -rf "$DOCS_OUT" 2>/dev/null || ! mkdir -p "$DOCS_OUT" 2>/dev/null; then
    # Do NOT attempt interactive `sudo` here — this runs non-interactively as the
    # npm prebuild hook / systemd ExecStartPre, where sudo would hang on the
    # password prompt. Fail fast with a clear, actionable message instead.
    echo -e "${RED}✗${NC} Cannot write $DOCS_OUT — public/ is owned by another user (likely root)."
    echo -e "   Fix once with: ${YELLOW}sudo chown -R vpt_user:vpt_user $(cd .. && pwd)${NC}"
    exit 1
fi

# 1. Copy OpenAPI HTML docs (generated by export_postman_specs.py)
echo -e "${GREEN}✓${NC} Copying OpenAPI HTML docs"
if [ -d "../docs/api/docs" ]; then
  mkdir -p "$DOCS_OUT/api/openapi"
  cp -r ../docs/api/docs/* "$DOCS_OUT/api/openapi/" 2>/dev/null || echo "Warning: No OpenAPI docs found"
else
  echo "Warning: OpenAPI docs directory not found"
fi

# 1.1 Copy raw OpenAPI YAML specs for interactive docs
echo -e "${GREEN}✓${NC} Copying OpenAPI YAML specs"
if [ -d "../docs/api/specs" ]; then
  mkdir -p "$DOCS_OUT/api/specs"
  cp -r ../docs/api/specs/* "$DOCS_OUT/api/specs/" 2>/dev/null || echo "Warning: No OpenAPI specs found"
else
  echo "Warning: OpenAPI specs directory not found"
fi

# 1.2 Copy interactive API docs shell
if [ -f "scripts/assets/interactive-api-docs.html" ]; then
  mkdir -p "$DOCS_OUT/api"
  cp "scripts/assets/interactive-api-docs.html" "$DOCS_OUT/api/interactive.html"
else
  echo "Warning: interactive API docs template not found"
fi

# 2. Copy only referenced markdown files
echo -e "${GREEN}✓${NC} Finding and copying referenced markdown files"

# Temporary files to track what to copy
TEMP_DIR=$(mktemp -d)
FILES_TO_COPY="$TEMP_DIR/files_to_copy.txt"
PROCESSED="$TEMP_DIR/processed.txt"

touch "$FILES_TO_COPY"
touch "$PROCESSED"

# Start with main README and section READMEs (entry points)
cat > "$FILES_TO_COPY" << EOF
README.md
get-started/README.md
get-started/install.md
get-started/add-a-host.md
get-started/docker.md
get-started/proxmox.md
get-started/local-dev.md
get-started/supabase.md
get-started/configuration.md
get-started/ci_cd.md
get-started/hardware.md
get-started/emulators.md
get-started/network.md
get-started/security.md
release_note/README.md
bugs/README.md
features/README.md
user-guide/README.md
technical/README.md
api/README.md
mcp/README.md
examples/README.md
integrations/README.md
screenshots/README.md
videos/README.md
mcp/mcp_tools_generated.md
EOF

echo -e "${YELLOW}→${NC} Following markdown links recursively"

# Process files iteratively
while IFS= read -r file; do
    # Skip if already processed
    if grep -Fxq "$file" "$PROCESSED" 2>/dev/null; then
        continue
    fi
    
    # Mark as processed
    echo "$file" >> "$PROCESSED"
    
    # Skip if file doesn't exist
    if [ ! -f "../docs/$file" ]; then
        continue
    fi
    
    # Find all markdown links in this file
    current_dir=$(dirname "$file")
    
    # Extract .md links from markdown
    grep -oE '\]\([^)]*\.md\)' "../docs/$file" 2>/dev/null | \
    sed 's/][(]//g' | sed 's/)//g' | \
    while IFS= read -r link; do
        # Resolve relative path safely
        target_dir_path="../docs/$current_dir/$(dirname "$link")"
        
        # Skip if directory doesn't exist (avoids cd errors)
        if [ ! -d "$target_dir_path" ]; then
            continue
        fi
        
        # Resolve absolute paths to check boundaries
        abs_target_dir=$(cd "$target_dir_path" && pwd)
        abs_docs_root=$(cd "../docs" && pwd)
        
        # Skip if the file is outside the docs directory
        if [[ "$abs_target_dir" != "$abs_docs_root"* ]]; then
            continue
        fi
        
        # Construct the resolved path relative to docs root
        abs_file_path="$abs_target_dir/$(basename "$link")"
        resolved="${abs_file_path#$abs_docs_root/}"

        # Internal-only trees — never ship to the public site, even if some other doc
        # happens to link into one of them:
        #   agent/    engineer/AI-agent reference (release process, infra layout, customer
        #             overlay names, hardware debug playbooks)
        #   tasks/    internal planning docs (customer overlay decisions, not user-facing)
        #   goals/    internal planning docs
        #   handover/ internal incident/handover notes
        #   security/ Bandit/Snyk/npm-audit output — now served admin-only via
        #             GET /server/security/* instead (see server_security_routes.py)
        #   technical/dev/ contributor-only implementation notes (naming conventions,
        #             z-index registry, undo/redo internals, detection design docs).
        #             Useless to a VirtualPyTest *user* and stale the moment the code
        #             moves — keep them in the repo for engineers, off the public site.
        #
        # bugs/ is NOT excluded (BUG-0081): the tracker is published, and the 14 files that
        # named lab addresses, customer site hostnames or a customer bundle name were
        # anonymized in place instead (docs/agent/release/ANONYMIZATION.md). Keeping it
        # publishable is a standing obligation on every new BUG file — the leak gate
        # (scripts/security/leak_gate.sh) enforces the identifier half on every push.
        case "$resolved" in
            agent/*|tasks/*|goals/*|handover/*|security/*|technical/dev/*) continue ;;
        esac

        # Add to files to copy if not already there
        if [ -f "../docs/$resolved" ] && ! grep -Fxq "$resolved" "$FILES_TO_COPY" 2>/dev/null; then
            echo "$resolved" >> "$FILES_TO_COPY"
        fi
    done
    
done < "$FILES_TO_COPY"

# Copy all found files
file_count=0
sort -u "$FILES_TO_COPY" | while IFS= read -r file; do
    if [ -f "../docs/$file" ]; then
        target_dir="$DOCS_OUT/$(dirname "$file")"
        mkdir -p "$target_dir"
        cp "../docs/$file" "$DOCS_OUT/$file"
        ((file_count++)) || true
    fi
done

# Images. Pages reference pictures relatively (get-started/hardware.md -> images/ms-a2.jpg),
# so ship docs/<section>/images/* next to every published section. Excluded trees (tasks/,
# agent/...) never reach FILES_TO_COPY, so their images/ folders are never shipped either.
sort -u "$FILES_TO_COPY" | xargs -n1 dirname | sort -u | while IFS= read -r dir; do
    if [ -d "../docs/$dir/images" ]; then
        mkdir -p "$DOCS_OUT/$dir/images"
        cp "../docs/$dir/images/"* "$DOCS_OUT/$dir/images/"
        echo -e "${GREEN}✓${NC} Copied images for $dir"
    fi
done

# For screenshots and videos: use index.md (styled version) instead of README.md
# This keeps GitHub showing README.md while website uses the styled index.md
if [ -f "../docs/screenshots/index.md" ]; then
    cp "../docs/screenshots/index.md" "$DOCS_OUT/screenshots/README.md"
    echo -e "${GREEN}✓${NC} Using styled index.md for screenshots"
fi
if [ -f "../docs/videos/index.md" ]; then
    cp "../docs/videos/index.md" "$DOCS_OUT/videos/README.md"
    echo -e "${GREEN}✓${NC} Using styled index.md for videos"
fi

# Count actual copied files
file_count=$(find "$DOCS_OUT" -name "*.md" | wc -l | tr -d ' ')

# Cleanup
rm -rf "$TEMP_DIR"

# 3. Security reports (Bandit/Snyk/npm-audit, see docs/security/README.md) are internal
# engineering tooling output — file paths, dependency versions and finding counts that are
# useful recon for an attacker and irrelevant to a docs reader. Deliberately NOT copied to the
# public site; keep reviewing them locally via `docs/security/index.html`.

echo -e "${GREEN}✓ Documentation copied successfully!${NC}"
echo -e "${BLUE}Copied: 15 OpenAPI HTML files + $file_count markdown files${NC}"

# 4. Generate docs manifest for navigation
echo -e "${YELLOW}→${NC} Generating docs manifest..."

# Generate manifest JSON by scanning the copied docs
node -e "
const fs = require('fs');
const path = require('path');

const DOCS_DIR = process.env.DOCS_OUT;

// Section metadata. Titles are plain text -- the navigator in Documentation.tsx
// draws the icon, keyed by the section slug, so every row matches the rest of the app.
const SECTION_META = {
  'README': { title: 'Documentation Home', order: 0 },
  'get-started': { title: 'Getting Started', order: 1 },
  'release_note': { title: 'Release Note', order: 2.5 },
  'features': { title: 'Features', order: 3 },
  'user-guide': { title: 'User Guide', order: 4 },
  'examples': { title: 'Examples', order: 5 },
  'integrations': { title: 'Integrations', order: 6 },
  'faq': { title: 'FAQ', order: 7 },
  'technical': { title: 'Technical Docs', order: 8 },
  'ai agent': { title: 'AI Agent', order: 9 },
  'api': { title: 'API Reference', order: 11 },
  'screenshots': { title: 'Screenshots', order: 12 },
  'videos': { title: 'Videos', order: 13 },
  // No order of their own: 99 keeps them where they already sit, after Videos. These two
  // exist only so the title is not toTitle()'d into 'Mcp'.
  'bugs': { title: 'Bugs', order: 99 },
  'mcp': { title: 'MCP Tools', order: 99 },
};

// Subsection metadata for technical docs
const TECH_SUBSECTION_META = {
  'ai': { title: 'AI', order: 1 },
  'architecture': { title: 'Architecture', order: 2 },
  'components': { title: 'Components', order: 3 },
  'mcp': { title: 'MCP Tools', order: 4 },
  'dev': { title: 'Dev', order: 5 },
};

// Convert filename to readable title
function toTitle(filename) {
  return filename
    .replace(/\.md\$/, '')
    .replace(/^README\$/, 'Overview')
    .replace(/[-_]/g, ' ')
    .replace(/\\b\\w/g, c => c.toUpperCase())
    .replace(/^Mcp /, 'MCP ')
    .replace(/^Ai /, 'AI ')
    .replace(/^Api /, 'API ')
    .replace(/ Id\$/, ' ID')
    .replace(/Jira/, 'JIRA')
    .replace(/Hls/, 'HLS')
    .replace(/Vnc/, 'VNC')
    .replace(/Avq/, 'AVQ');
}

// Get all markdown files in a directory
function getMdFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .sort((a, b) => {
      // README first, then alphabetically
      if (a === 'README.md') return -1;
      if (b === 'README.md') return 1;
      return a.localeCompare(b);
    });
}

// Get all subdirectories
function getSubdirs(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => fs.statSync(path.join(dir, f)).isDirectory())
    .filter(f => !f.startsWith('.') && f !== 'openapi');
}

// Build section children
function buildChildren(sectionPath, urlPrefix) {
  const children = [];
  const files = getMdFiles(sectionPath);
  const subdirs = getSubdirs(sectionPath);
  
  // Add files
  files.forEach(file => {
    const name = file.replace('.md', '');
    const docPath = name === 'README' ? urlPrefix : urlPrefix + '/' + name;
    children.push({
      title: toTitle(file),
      path: docPath
    });
  });
  
  // Add subdirectories
  subdirs.forEach(subdir => {
    const subPath = path.join(sectionPath, subdir);
    const subFiles = getMdFiles(subPath);
    const subSubdirs = getSubdirs(subPath);
    
    if (subFiles.length > 0 || subSubdirs.length > 0) {
      const meta = TECH_SUBSECTION_META[subdir] || { title: toTitle(subdir), order: 99 };
      const subChildren = [];
      
      // Add subdir files (skip README - paths don't work with routing)
      subFiles.forEach(file => {
        if (file === 'README.md') return; // Skip README in nested dirs
        const name = file.replace('.md', '');
        const docPath = urlPrefix + '/' + subdir + '/' + name;
        subChildren.push({
          title: toTitle(file),
          path: docPath
        });
      });
      
      // Handle nested subdirs (like components under architecture)
      subSubdirs.forEach(nestedDir => {
        const nestedPath = path.join(subPath, nestedDir);
        const nestedFiles = getMdFiles(nestedPath);
        
        if (nestedFiles.length > 0) {
          const nestedMeta = TECH_SUBSECTION_META[nestedDir] || { title: toTitle(nestedDir), order: 99 };
          // Skip README files in deeply nested dirs
          const nestedChildren = nestedFiles
            .filter(file => file !== 'README.md')
            .map(file => {
              const name = file.replace('.md', '');
              const docPath = urlPrefix + '/' + subdir + '/' + nestedDir + '/' + name;
              return { title: toTitle(file), path: docPath };
            });
          
          if (nestedChildren.length > 0) {
            subChildren.push({
              title: nestedMeta.title,
              children: nestedChildren
            });
          }
        }
      });
      
      if (subChildren.length > 0) {
        children.push({
          title: meta.title,
          children: subChildren
        });
      }
    }
  });
  
  return children;
}

// Build the manifest
const manifest = { docs: [] };

// Get top-level sections
const topLevelDirs = getSubdirs(DOCS_DIR);
const sections = [];

// Add root README if exists
if (fs.existsSync(path.join(DOCS_DIR, 'README.md'))) {
  sections.push({
    title: SECTION_META['README'].title,
    path: '/docs/README',
    section: 'root',
    order: SECTION_META['README'].order
  });
}

// Process each section
topLevelDirs.forEach(dir => {
  const sectionPath = path.join(DOCS_DIR, dir);
  const meta = SECTION_META[dir] || { title: toTitle(dir), order: 99 };
  const urlPrefix = '/docs/' + dir;
  
  const children = buildChildren(sectionPath, urlPrefix);
  
  if (children.length > 0) {
    sections.push({
      title: meta.title,
      path: urlPrefix,
      section: dir,
      order: meta.order,
      children: children
    });
  }
});

// Sort by order
sections.sort((a, b) => a.order - b.order);

// Remove order field from output
sections.forEach(s => delete s.order);

manifest.docs = sections;

// Write manifest
fs.writeFileSync(path.join(DOCS_DIR, 'docs-manifest.json'), JSON.stringify(manifest, null, 2));
console.log('Generated docs-manifest.json with ' + sections.length + ' sections');
"

echo -e "${GREEN}✓ Docs manifest generated!${NC}"

# ==================== SWAP STAGING INTO PLACE ====================
# Everything above wrote to $DOCS_OUT, so public/docs still holds the previous (working)
# copy right up to this point. Refuse to swap in a staging tree that is obviously
# incomplete — an empty or markdown-less build is worse than keeping the old docs.
if [ ! -f "$DOCS_OUT/docs-manifest.json" ] || [ "$file_count" -eq 0 ]; then
    echo -e "${RED}✗${NC} Staged docs look incomplete (${file_count} markdown files, manifest missing?) — keeping existing $DOCS_FINAL"
    exit 1
fi

DOCS_PREV="public/.docs-prev.$$"
rm -rf "$DOCS_PREV"
if [ -d "$DOCS_FINAL" ]; then
    mv "$DOCS_FINAL" "$DOCS_PREV"
fi
if ! mv "$DOCS_OUT" "$DOCS_FINAL"; then
    # Put the previous docs back rather than leaving the site with none.
    [ -d "$DOCS_PREV" ] && mv "$DOCS_PREV" "$DOCS_FINAL"
    echo -e "${RED}✗${NC} Could not swap $DOCS_OUT into $DOCS_FINAL — previous docs restored"
    exit 1
fi
rm -rf "$DOCS_PREV"

echo -e "${GREEN}✓ Docs published to $DOCS_FINAL ($file_count markdown files)${NC}"
