#!/usr/bin/env python3
"""
TV DOM exporter using OmniParser detections plus local TV focus/navigation logic.

Input is an OmniParser normalized JSON file generated by the benchmark run:
    /tmp/dom_benchmark/omni_full/<stem>_normalized.json

The output format intentionally mirrors ui_dom_exporter.py:
    elements: focusable TV elements after filtering/merging
    focused_element_id: focus cue associated to one of those elements
    navigation: LEFT/RIGHT/UP/DOWN/OK/BACK graph inferred from layout rows
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import cv2

HERE = Path(__file__).resolve().parent


def _load_module(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, str(HERE / filename))
    mod = importlib.util.module_from_spec(spec)
    assert spec and spec.loader
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


focusmod = _load_module("focus_detector", "no_reference_focus_detector.py")


@dataclass
class Element:
    id: str
    type: str
    label: str
    x: float
    y: float
    w: float
    h: float
    row: str = ""
    focused: bool = False
    source: str = ""
    score: float = 0.0

    @property
    def cx(self) -> float:
        return self.x + self.w / 2

    @property
    def cy(self) -> float:
        return self.y + self.h / 2

    @property
    def end(self) -> float:
        return self.x + self.w

    @property
    def bottom(self) -> float:
        return self.y + self.h


def slug(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_") or "item"


def _clean_label(label: str) -> str:
    label = re.sub(r"\s+", " ", str(label or "")).strip()
    label = label.strip("|_.,;:()[]{}")
    return label


def _words(label: str) -> List[str]:
    return [w for w in re.split(r"\s+", _clean_label(label)) if w]


def _iou(a: Element, b: Tuple[float, float, float, float]) -> float:
    x, y, w, h = b
    ix0, iy0 = max(a.x, x), max(a.y, y)
    ix1, iy1 = min(a.end, x + w), min(a.bottom, y + h)
    inter = max(0.0, ix1 - ix0) * max(0.0, iy1 - iy0)
    if inter <= 0:
        return 0.0
    return inter / max(1e-9, (a.w * a.h + w * h - inter))


def _contains(inner: Element, outer: Element, margin: float = 0.0) -> bool:
    return (
        outer.x - margin <= inner.cx <= outer.end + margin
        and outer.y - margin <= inner.cy <= outer.bottom + margin
    )


def _overlap_ratio(a: Element, b: Element) -> float:
    ix0, iy0 = max(a.x, b.x), max(a.y, b.y)
    ix1, iy1 = min(a.end, b.end), min(a.bottom, b.bottom)
    inter = max(0.0, ix1 - ix0) * max(0.0, iy1 - iy0)
    return inter / max(1e-9, min(a.w * a.h, b.w * b.h))


def load_omni_elements(omni_json_path: str) -> Tuple[List[Element], List[Element], Dict[str, Any]]:
    with open(omni_json_path, "r", encoding="utf-8") as f:
        dom = json.load(f)

    texts: List[Element] = []
    icons: List[Element] = []
    for idx, item in enumerate(dom.get("elements", [])):
        bbox = item.get("bbox") or [0, 0, 0, 0]
        if len(bbox) != 4:
            continue
        x, y, w, h = [float(v) for v in bbox]
        if w <= 0 or h <= 0:
            continue
        elem = Element(
            id=f"omni_{idx}",
            type=str(item.get("type") or "element"),
            label=_clean_label(item.get("content") or ""),
            x=x,
            y=y,
            w=w,
            h=h,
            source=str(item.get("source") or "omni"),
        )
        if elem.type == "text":
            texts.append(elem)
        elif elem.type == "icon":
            icons.append(elem)
    return texts, icons, dom


def _candidate_type(e: Element) -> str:
    label = e.label.lower()
    words = _words(e.label)
    area = e.w * e.h
    aspect = e.w / max(e.h, 1e-6)

    action_labels = {
        "play",
        "resume",
        "continue",
        "watch",
        "anschauen",
        "ok",
        "more",
        "details",
        "suggested",
        "episodes",
        "settings",
        "profiles",
        "system",
        "info",
    }
    if label in action_labels or any(label.startswith(v + " ") for v in action_labels):
        return "button"
    if e.cy < 0.13 and len(words) <= 3 and 0.018 <= e.h <= 0.095 and e.w <= 0.20:
        return "nav_item"
    # Modal/menu rows are wider than normal buttons but still focusable.
    if e.source.startswith("box_yolo") and len(words) <= 4 and 0.04 <= e.h <= 0.15 and 0.12 <= e.w <= 0.58:
        return "button"
    if 0.045 <= e.w <= 0.25 and 0.045 <= e.h <= 0.35 and area <= 0.08:
        if aspect < 5.0:
            return "card"
    if e.source.startswith("box_yolo") and area <= 0.09 and 0.03 <= e.w <= 0.35 and 0.035 <= e.h <= 0.18:
        return "button"
    return "candidate"


def _is_sentence_text(e: Element) -> bool:
    words = _words(e.label)
    if len(words) > 3:
        return True
    if len(e.label) > 35 and e.h < 0.08:
        return True
    if e.w > 0.35 and e.h < 0.10 and len(words) > 2:
        return True
    return False


def label_icons_from_text(icons: List[Element], texts: List[Element]) -> None:
    for icon in icons:
        if icon.label:
            continue
        nearby = []
        for text in texts:
            if _is_sentence_text(text):
                continue
            inside = _contains(text, icon, margin=0.01)
            below = icon.bottom <= text.cy <= icon.bottom + 0.075 and icon.x - 0.02 <= text.cx <= icon.end + 0.02
            above = icon.y - 0.055 <= text.cy <= icon.y and icon.x - 0.02 <= text.cx <= icon.end + 0.02
            if inside or below or above:
                nearby.append(text)
        if nearby:
            nearby.sort(key=lambda t: (t.y, t.x))
            icon.label = _clean_label(" ".join(t.label for t in nearby[:3]))


def build_interactive_candidates(texts: List[Element], icons: List[Element]) -> List[Element]:
    label_icons_from_text(icons, texts)
    candidates: List[Element] = []

    for icon in icons:
        area = icon.w * icon.h
        if icon.w < 0.02 or icon.h < 0.02:
            continue
        if area > 0.25:
            continue
        if icon.w > 0.65 or icon.h > 0.65:
            continue
        icon.type = _candidate_type(icon)
        if icon.type == "candidate":
            if icon.source.startswith("box_yolo") and len(_words(icon.label)) <= 4 and 0.04 <= icon.h <= 0.16 and icon.w <= 0.58:
                icon.type = "button"
                candidates.append(icon)
                continue
            # Keep only plausible unlabeled visual controls/cards.
            if not (0.03 <= icon.w <= 0.28 and 0.03 <= icon.h <= 0.35):
                continue
            icon.type = "card"
        candidates.append(icon)

    for text in texts:
        if not text.label:
            continue
        if text.w < 0.02 or text.h < 0.018:
            continue
        if _is_sentence_text(text):
            continue
        text.type = _candidate_type(text)
        if text.type not in {"nav_item", "button", "card"}:
            continue
        # Text-only OCR boxes are labels/body text unless they are compact nav
        # tabs or known action buttons. Do not promote arbitrary OCR labels to
        # focusable cards.
        if text.source == "box_ocr_content_ocr" and text.type == "card":
            continue
        # Avoid adding text labels already represented by an icon/card.
        if any(_contains(text, icon, margin=0.015) or _overlap_ratio(text, icon) > 0.5 for icon in candidates):
            continue
        candidates.append(text)

    # Remove near-duplicates, keeping larger/labelled boxes first.
    candidates.sort(key=lambda e: (bool(e.label), e.w * e.h), reverse=True)
    kept: List[Element] = []
    for e in candidates:
        if any(_overlap_ratio(e, k) > 0.82 for k in kept):
            continue
        kept.append(e)

    kept.sort(key=lambda e: (e.cy, e.x))
    for idx, e in enumerate(kept):
        label_slug = slug(e.label) if e.label else "item"
        e.id = f"{e.type}_{idx}_{label_slug}"
    return kept


def associate_focus(img, elements: List[Element]) -> Tuple[Optional[str], List[dict]]:
    candidates = focusmod.detect_focus(img, top_k=8)
    if not candidates:
        return None, []

    best_el: Optional[Element] = None
    best_score = -1.0
    h, w = img.shape[:2]
    for rank, cand in enumerate(candidates):
        x, y, bw, bh = cand.box
        fb = (x / w, y / h, bw / w, bh / h)
        focus_area = fb[2] * fb[3]
        fcx, fcy = fb[0] + fb[2] / 2, fb[1] + fb[3] / 2
        for e in elements:
            overlap = _iou(e, fb)
            # Colored logos inside artwork often look like focus rings/fills. A
            # real border/ring should cover a meaningful portion of the matched
            # element, unless IoU is already strong.
            if cand.cue_type in {"border_or_ring", "avatar_ring_or_fill"}:
                if overlap < 0.25 and focus_area < (e.w * e.h * 0.45):
                    continue
            score = overlap * 4.0 - rank * 1.25
            if e.x - 0.025 <= fcx <= e.end + 0.025 and e.y - 0.025 <= fcy <= e.bottom + 0.035:
                score += 0.85
            if cand.cue_type == "underline" and e.type == "nav_item":
                score += max(0.0, 1.0 - abs(e.cx - fcx) / 0.09)
            if cand.cue_type in {"border_or_ring", "avatar_ring_or_fill"} and e.type in {"card", "button"}:
                score += max(0.0, 0.9 - abs(e.cx - fcx) / 0.15 - abs(e.cy - fcy) / 0.15)
            if cand.cue_type == "filled_highlight" and e.type in {"button", "card"}:
                score += max(0.0, 0.8 - abs(e.cx - fcx) / 0.18 - abs(e.cy - fcy) / 0.18)
            if score > best_score:
                best_score = score
                best_el = e

    if best_el is not None and best_score > 0.55:
        for e in elements:
            e.focused = False
        best_el.focused = True
        return best_el.id, [asdict(c) for c in candidates]
    return None, [asdict(c) for c in candidates]


def group_rows(elements: List[Element], row_tol: float = 0.075) -> List[List[Element]]:
    rows: List[List[Element]] = []
    for e in sorted(elements, key=lambda z: (z.cy, z.x)):
        placed = False
        for row in rows:
            avg = sum(z.cy for z in row) / len(row)
            # Larger elements can span a row; use adaptive tolerance.
            tol = max(row_tol, min(0.13, max(e.h, max(z.h for z in row)) * 0.55))
            if abs(e.cy - avg) <= tol:
                row.append(e)
                placed = True
                break
        if not placed:
            rows.append([e])
    for row in rows:
        row.sort(key=lambda z: z.x)
    rows.sort(key=lambda row: sum(e.cy for e in row) / len(row))
    for ri, row in enumerate(rows):
        for ci, e in enumerate(row):
            e.row = f"row_{ri}"
            if not e.id:
                e.id = f"{e.type}_{ri}_{ci}_{slug(e.label)}"
    return rows


def nearest_by_x(source: Element, row: List[Element]) -> Optional[Element]:
    if not row:
        return None
    return min(row, key=lambda e: abs(e.cx - source.cx) + max(0.0, abs(e.w - source.w)) * 0.08)


def navigation_from_rows(screen_id: str, rows: List[List[Element]]) -> Dict[str, Dict[str, str]]:
    nav: Dict[str, Dict[str, str]] = {}
    for ri, row in enumerate(rows):
        for ci, e in enumerate(row):
            edges: Dict[str, str] = {"OK": f"ENTER:{e.label or e.type}", "BACK": "UNKNOWN"}
            if ci > 0:
                edges["LEFT"] = f"{screen_id}.{row[ci - 1].id}"
            if ci < len(row) - 1:
                edges["RIGHT"] = f"{screen_id}.{row[ci + 1].id}"
            if ri > 0:
                target = nearest_by_x(e, rows[ri - 1])
                if target:
                    edges["UP"] = f"{screen_id}.{target.id}"
            if ri < len(rows) - 1:
                target = nearest_by_x(e, rows[ri + 1])
                if target:
                    edges["DOWN"] = f"{screen_id}.{target.id}"
            nav[f"{screen_id}.{e.id}"] = edges
    return nav


def infer_dom(image_path: str, omni_json_path: str) -> Dict[str, Any]:
    img = cv2.imread(image_path)
    if img is None:
        raise FileNotFoundError(image_path)
    texts, icons, omni_raw = load_omni_elements(omni_json_path)
    elements = build_interactive_candidates(texts, icons)
    focused_id, focus_candidates = associate_focus(img, elements)
    screen_id = Path(image_path).stem
    rows = group_rows(elements)
    nav = navigation_from_rows(screen_id, rows)
    return {
        "image": Path(image_path).name,
        "screen_id": screen_id,
        "focused_element_id": focused_id,
        "elements": [asdict(e) for e in elements],
        "navigation": nav,
        "focus_candidates": focus_candidates[:5],
        "omni_source": omni_json_path,
        "omni_raw_count": len(omni_raw.get("elements", [])),
    }


def draw_dom(image_path: str, dom: Dict[str, Any], out_path: str) -> None:
    img = cv2.imread(image_path)
    h, w = img.shape[:2]
    colors = {"nav_item": (0, 255, 255), "card": (255, 180, 0), "button": (255, 0, 255)}
    for e in dom.get("elements", []):
        x, y, bw, bh = e["x"], e["y"], e["w"], e["h"]
        x0, y0 = int(x * w), int(y * h)
        x1, y1 = int((x + bw) * w), int((y + bh) * h)
        color = (0, 0, 255) if e.get("focused") else colors.get(e.get("type"), (180, 180, 180))
        cv2.rectangle(img, (x0, y0), (x1, y1), color, 3 if e.get("focused") else 2)
        label = f"{e.get('type')}:{e.get('label') or e.get('id')}"
        cv2.putText(img, label[:36], (x0, max(18, y0 - 5)), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color, 1, cv2.LINE_AA)
    cv2.imwrite(out_path, img)


def export_dom_files(image_path: str, dom: Dict[str, Any], out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    stem = Path(image_path).stem
    draw_dom(image_path, dom, os.path.join(out_dir, f"{stem}_dom.jpg"))
    with open(os.path.join(out_dir, f"{stem}_dom.json"), "w", encoding="utf-8") as f:
        json.dump(dom, f, indent=2, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("images", nargs="+")
    parser.add_argument("--omni-out", default="/tmp/dom_benchmark/omni_full")
    parser.add_argument("--out", default="/tmp/omni_tv_dom_out")
    args = parser.parse_args()

    results = []
    for image_path in args.images:
        stem = Path(image_path).stem
        omni_json = os.path.join(args.omni_out, f"{stem}_normalized.json")
        try:
            dom = infer_dom(image_path, omni_json)
            export_dom_files(image_path, dom, args.out)
            results.append(dom)
            print(
                f"{Path(image_path).name:28s} elems={len(dom['elements']):2d} "
                f"focus={dom.get('focused_element_id') or '-'} nav={len(dom['navigation'])}"
            )
        except Exception as exc:
            print(f"{Path(image_path).name:28s} FAILED {type(exc).__name__}: {exc}")
    with open(os.path.join(args.out, "dom_results.json"), "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    main()
