"""
Action tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in action_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for action.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/action_tools.py docstrings
    """
    return [
    {
        "name": "execute_device_action",
        "description": "Execute batch of actions on a device. Supports remote commands, ADB, web actions, desktop automation. Automatically acquires and releases device lock. COMMON ACTION FORMATS BY DEVICE TYPE: \ud83d\udcf1 MOBILE DEVICES (android_mobile, android_tv): - click_element: {\"command\": \"click_element\", \"params\": {\"text\": \"Button Text\", \"wait_time\": 1000, \"iteration\": 1}} * text: Element text to click (REQUIRED) * wait_time: Milliseconds to wait after click (default: 1000) - click_element_by_id: BLOCKED for mobile devices (unreliable on ADB) \ud83c\udf10 WEB DEVICES (host_vnc, web): - click_element: {\"command\": \"click_element\", \"params\": {\"text\": \"Button Text\", \"wait_time\": 1000}} * text: Visible text of element to click (REQUIRED) * xpath: XPath selector (alternative to text) * wait_time: Milliseconds to wait after click (default: 1000) - click_element_by_id: {\"command\": \"click_element_by_id\", \"params\": {\"element_id\": \"btn-submit\", \"wait_time\": 1000}} * element_id: HTML element ID attribute (REQUIRED) * wait_time: Milliseconds to wait after click (default: 1000) - navigate: {\"command\": \"navigate\", \"params\": {\"url\": \"https://example.com\"}} * url: URL to navigate to (REQUIRED) \ud83c\udfae REMOTE CONTROLS: - KEY_HOME: {\"command\": \"KEY_HOME\"} (no params needed) - KEY_BACK: {\"command\": \"KEY_BACK\"} (no params needed) - Custom keys: {\"command\": \"KEY_CUSTOM\", \"params\": {\"key\": \"KEY_ENTER\"}} * key: Key code/name (REQUIRED) \u26a0\ufe0f COMMON MISTAKES TO AVOID: - Don't use \"click\" command - use \"click_element\" instead - Always wrap parameters in \"params\": {...} object - For mobile: use \"text\" parameter, not \"element_id\" - Check device type - some commands are blocked per device model MCP-formatted response with execution results\n\nExample: execute_device_action(host_name='host1', device_id='device1', actions=[{'command': 'click_element', 'params': {'text': 'Replay'}}])",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "actions": {
                    "type": "array",
                    "description": "list of action dicts with command and params"
                },
                "force_unlock": {
                    "type": "boolean",
                    "description": "preempt existing lock if device is locked"
                },
                "include_screenshot": {
                    "type": "boolean",
                    "description": "include a device screenshot of the resulting screen in the response, default false"
                }
            },
            "required": [
                "host_name",
                "device_id",
                "actions"
            ]
        }
    },
    {
        "name": "list_actions",
        "description": "List available actions for a device. MCP-formatted response with categorized list of available actions\n\nExample: list_actions(host_name='host1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    }
]
