"""
Campaign tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in campaign_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 6 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for campaign.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/campaign_tools.py docstrings
    """
    return [
    {
        "name": "create_campaign",
        "description": "Create a new test campaign MCP-formatted response with created campaign details",
        "inputSchema": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string",
                    "description": "Campaign name"
                },
                "campaign_description": {
                    "type": "string",
                    "description": "Campaign description"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "User interface name"
                },
                "script_configurations": {
                    "type": "array",
                    "description": "List of scripts with parameters"
                },
                "execution_config": {
                    "type": "object",
                    "description": "Execution configuration"
                }
            },
            "required": [
                "campaign_name",
                "script_configurations"
            ]
        }
    },
    {
        "name": "delete_campaign",
        "description": "Delete a campaign MCP-formatted response confirming deletion",
        "inputSchema": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string",
                    "description": "Campaign name"
                }
            },
            "required": [
                "campaign_name"
            ]
        }
    },
    {
        "name": "execute_campaign",
        "description": "Execute a test campaign MCP-formatted response with execution status",
        "inputSchema": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string",
                    "description": "Campaign name to execute"
                },
                "host_name": {
                    "type": "string",
                    "description": "Host name where devices are located"
                },
                "device_name": {
                    "type": "string",
                    "description": "Device name for execution"
                }
            },
            "required": [
                "campaign_name",
                "host_name",
                "device_name"
            ]
        }
    },
    {
        "name": "get_campaign",
        "description": "Get details of a specific campaign MCP-formatted response with campaign details",
        "inputSchema": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string",
                    "description": "Campaign name"
                }
            },
            "required": [
                "campaign_name"
            ]
        }
    },
    {
        "name": "list_campaigns",
        "description": "List all campaigns for a team MCP-formatted response with list of campaigns",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "update_campaign",
        "description": "Update an existing campaign MCP-formatted response with updated campaign details",
        "inputSchema": {
            "type": "object",
            "properties": {
                "campaign_name": {
                    "type": "string",
                    "description": "Current campaign name to update"
                },
                "new_campaign_name": {
                    "type": "string",
                    "description": "New campaign name"
                },
                "campaign_description": {
                    "type": "string",
                    "description": "New campaign description"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "New user interface name"
                },
                "script_configurations": {
                    "type": "array",
                    "description": "Updated script configurations"
                },
                "execution_config": {
                    "type": "object",
                    "description": "Updated execution configuration"
                }
            },
            "required": [
                "campaign_name"
            ]
        }
    }
]
