"""
Logs tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in logs_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for logs.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/logs_tools.py docstrings
    """
    return [
    {
        "name": "list_services",
        "description": "List available systemd services for monitoring. MCP-formatted response with available services\n\nExample: list_services()",
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
    {
        "name": "view_logs",
        "description": "View systemd service logs via journalctl Access logs from backend_server, backend_host, or other services. Supports follow mode, filtering by time, and limiting lines. MCP-formatted response with log output",
        "inputSchema": {
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "description": "Service name (e.g., 'vpt-server', 'vpt-host', 'vpt-frontend'"
                },
                "lines": {
                    "type": "integer",
                    "description": "Number of recent lines (default: 50"
                },
                "follow": {
                    "type": "boolean",
                    "description": "Follow mode (default: False"
                },
                "since": {
                    "type": "string",
                    "description": "Show logs since time (e.g., '1h', '30min', '2024-01-04 12:00'"
                },
                "level": {
                    "type": "string",
                    "description": "Filter by log level ('emerg', 'alert', 'crit', 'err', 'warning', 'notice', 'info', 'debug'"
                },
                "grep": {
                    "type": "string",
                    "description": "Filter logs by pattern"
                }
            },
            "required": [
                "service"
            ]
        }
    }
]
