"""
Script tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in script_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 2 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for script.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/script_tools.py docstrings
    """
    return [
    {
        "name": "execute_script",
        "description": (
            "Execute a Python script on a device. Automatically acquires a device lock for the duration of execution.\n\n"
            "⚠️ MANDATORY PREREQUISITE: You MUST call get_device_info() or get_compatible_hosts() BEFORE this tool "
            "to discover available host_name and device_id values. Do NOT guess device_id values.\n\n"
            "⚠️ DEVICE ID: The device_id MUST match an actual device on the host. Use get_device_info(host_name='...') "
            "to see exactly which device_ids exist. Wrong device_id will be rejected.\n\n"
            "Example: execute_script(script_name='dns_lookuptime.py', host_name='my-host', device_id='host')"
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "script_name": {
                    "type": "string",
                    "description": "Script filename (e.g., 'my_script.py')"
                },
                "host_name": {
                    "type": "string",
                    "description": "Host where device is located (from get_device_info or get_compatible_hosts)"
                },
                "device_id": {
                    "type": "string",
                    "description": "Device identifier (defaults to 'host' if not provided. Use get_device_info to find valid values)"
                },
                "parameters": {
                    "type": "string",
                    "description": "CLI parameters as string (e.g., '--param1 value1 --param2 value2')"
                },
                "force_unlock": {
                    "type": "boolean",
                    "description": "If true, preempt any existing lock on the device (default false)"
                }
            },
            "required": [
                "script_name",
                "host_name"
            ]
        }
    },
    {
        "name": "list_scripts",
        "description": (
            "List all available Python scripts with their target rules (device requirements).\n\n"
            "⚠️ IMPORTANT: Use this tool BEFORE execute_script to understand what device type each script requires. "
            "Each script includes target_rules that specify target_type, device_model, and host_os.\n\n"
            "After listing scripts, call get_device_info() or get_compatible_hosts() to find "
            "a matching host_name and device_id for the script you want to run.\n\n"
            "Example: list_scripts()"
        ),
        "inputSchema": {
            "type": "object",
            "properties": {},
            "required": []
        }
    }
]
