"""
Tree tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in tree_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 10 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for tree.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/tree_tools.py docstrings
    """
    return [
    {
        "name": "create_edge",
        "description": "Create an edge between two nodes. Accepts userinterface_name for auto-resolving tree_id. Created edge object\n\nExample: create_edge(userinterface_name='example_mobile', source_node_id='home', target_node_id='settings', source_label='home', target_label='settings', action_sets=[...])",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "source_node_id": {
                    "type": "string",
                    "description": "source node ID"
                },
                "target_node_id": {
                    "type": "string",
                    "description": "target node ID"
                },
                "source_label": {
                    "type": "string",
                    "description": "source node label"
                },
                "target_label": {
                    "type": "string",
                    "description": "target node label"
                },
                "action_sets": {
                    "type": "array",
                    "description": "array of action sets with bidirectional actions"
                }
            },
            "required": [
                "source_node_id",
                "target_node_id",
                "source_label",
                "target_label",
                "action_sets"
            ]
        }
    },
    {
        "name": "create_node",
        "description": "Create a node in navigation tree. Accepts userinterface_name for auto-resolving tree_id. IMPORTANT: Add verifications AFTER creation using update_node - they will be validated against device controllers. Created node object\n\nExample: create_node(userinterface_name='example_mobile', node_id='home', label='Home Screen')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier auto-generated if omitted"
                },
                "label": {
                    "type": "string",
                    "description": "node label or name"
                },
                "type": {
                    "type": "string",
                    "description": "node type default screen"
                },
                "position": {
                    "type": "object",
                    "description": "x y coordinates"
                },
                "data": {
                    "type": "object",
                    "description": "custom metadata"
                }
            },
            "required": [
                "label"
            ]
        }
    },
    {
        "name": "create_subtree",
        "description": "Create a subtree for a parent node. Accepts userinterface_name for auto-resolving parent_tree_id. Created subtree with new tree_id\n\nExample: create_subtree(userinterface_name='example_mobile', parent_node_id='menu', subtree_name='Menu Options')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "parent_tree_id": {
                    "type": "string",
                    "description": "parent tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving parent_tree_id"
                },
                "parent_node_id": {
                    "type": "string",
                    "description": "parent node ID to attach subtree"
                },
                "subtree_name": {
                    "type": "string",
                    "description": "name for the subtree"
                }
            },
            "required": [
                "parent_node_id",
                "subtree_name"
            ]
        }
    },
    {
        "name": "delete_edge",
        "description": "Delete an edge from navigation tree. Accepts userinterface_name for auto-resolving tree_id. Success confirmation\n\nExample: delete_edge(userinterface_name='example_mobile', edge_id='edge1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "edge_id": {
                    "type": "string",
                    "description": "edge identifier to delete"
                }
            },
            "required": [
                "edge_id"
            ]
        }
    },
    {
        "name": "delete_node",
        "description": "Delete a node from navigation tree. Accepts userinterface_name for auto-resolving tree_id. Success confirmation\n\nExample: delete_node(userinterface_name='example_mobile', node_id='home')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier to delete"
                }
            },
            "required": [
                "node_id"
            ]
        }
    },
    {
        "name": "get_edge",
        "description": "Get a specific edge by ID. Returns full edge object that can be modified and passed to update_edge. Example workflow: 1. result = get_edge(userinterface_name='example_mobile', edge_id='edge1') 2. edge = result['edge'] 3. edge['action_sets'][0]['actions'].append({'command': 'press_key', 'params': {'key': 'OK'}}) 4. update_edge(userinterface_name='example_mobile', edge=edge) Full edge object with all fields ready for modification and update_edge",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "edge_id": {
                    "type": "string",
                    "description": "edge identifier"
                }
            },
            "required": [
                "edge_id"
            ]
        }
    },
    {
        "name": "get_node",
        "description": "Get a specific node by ID. Returns full node object that can be modified and passed to update_node. Example workflow: 1. result = get_node(userinterface_name='example_mobile', node_id='home') 2. node = result['node'] 3. node['label'] = 'Home Screen New' 4. update_node(userinterface_name='example_mobile', node=node) Full node object with all fields ready for modification and update_node",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier"
                }
            },
            "required": [
                "node_id"
            ]
        }
    },
    {
        "name": "save_node_screenshot",
        "description": "Take screenshot and save it to a specific node. Wraps screenshot capture and node update into single operation. Success with screenshot URL and node ID\n\nExample: save_node_screenshot(tree_id='abc', node_id='home', label='Home Screen', host_name='host1', device_id='device1', userinterface_name='google_tv')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID"
                },
                "node_id": {
                    "type": "string",
                    "description": "node identifier to attach screenshot"
                },
                "label": {
                    "type": "string",
                    "description": "node label used as filename"
                },
                "host_name": {
                    "type": "string",
                    "description": "host where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "interface name for organizing screenshots"
                }
            },
            "required": [
                "tree_id",
                "node_id",
                "label",
                "host_name",
                "device_id",
                "userinterface_name"
            ]
        }
    },
    {
        "name": "update_edge",
        "description": "Update an existing edge with full edge object (same pattern as frontend). Use get_edge first to fetch the edge, modify it locally, then pass the full modified edge here. Action commands will be validated against available device controllers. Example workflow: 1. result = get_edge(userinterface_name='example_mobile', edge_id='edge1') 2. edge = result['edge'] 3. edge['action_sets'][0]['actions'].append({'command': 'press_key', 'params': {'key': 'OK'}}) 4. update_edge(userinterface_name='example_mobile', edge=edge) Updated edge confirmation",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "edge": {
                    "type": "object",
                    "description": "full edge object from get_edge with modifications"
                }
            },
            "required": [
                "edge"
            ]
        }
    },
    {
        "name": "update_node",
        "description": "Update an existing node with full node object (same pattern as frontend). Use get_node first to fetch the node, modify it locally, then pass the full modified node here. Verifications MUST be validated against available device controllers - saves will FAIL if invalid. Example workflow: 1. node = get_node(userinterface_name='example_mobile', node_id='home') 2. node['label'] = 'Home Screen New' 3. node['verifications'].append({'command': 'waitForElementToAppear', 'verification_type': 'adb', 'params': {'search_term': 'Home'}}) 4. update_node(userinterface_name='example_mobile', node=node) Updated node confirmation",
        "inputSchema": {
            "type": "object",
            "properties": {
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "UI name for auto-resolving tree_id"
                },
                "node": {
                    "type": "object",
                    "description": "full node object from get_node with modifications"
                }
            },
            "required": [
                "node"
            ]
        }
    }
]
