"""
Verification tool definitions - AUTO-GENERATED (DEBUG VIEW)

⚠️  DO NOT EDIT THIS FILE MANUALLY!
This file is auto-generated from docstrings in verification_tools.py
To change definitions, update the docstrings in the implementation.

Generated: 4 tools
"""

from typing import List, Dict, Any


def get_tools() -> List[Dict[str, Any]]:
    """
    Auto-generated tool definitions for verification.

    🔍 DEBUG VIEW: This file shows what was generated from docstrings.
    ⚠️  Source of truth: ../tools/verification_tools.py docstrings
    """
    return [
    {
        "name": "dump_ui_elements",
        "description": "Dump UI elements from current device screen REUSES existing verification endpoints MCP-formatted response with UI elements array",
        "inputSchema": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "defaults to 'device1'"
                },
                "host_name": {
                    "type": "string",
                    "description": "defaults to 'host1'"
                },
                "platform": {
                    "type": "string",
                    "description": "'mobile', 'web', 'tv'"
                }
            },
            "required": []
        }
    },
    {
        "name": "get_installed_apps",
        "description": "Get list of installed apps on Android device Uses the get_installed_apps method from ADBUtils MCP-formatted response with installed apps list",
        "inputSchema": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string",
                    "description": "defaults to 'device1'"
                },
                "host_name": {
                    "type": "string",
                    "description": "defaults to 'host1'"
                }
            },
            "required": []
        }
    },
    {
        "name": "list_verifications",
        "description": "List available verification types for a device. MCP-formatted response with categorized list of available verifications\n\nExample: list_verifications(host_name='host1', device_id='device1')",
        "inputSchema": {
            "type": "object",
            "properties": {
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                }
            },
            "required": [
                "host_name",
                "device_id"
            ]
        }
    },
    {
        "name": "verify_node",
        "description": "Execute verifications for a specific node. Runs embedded verifications using executeBatch endpoint. Uses node_label (human readable name) by default. Auto-resolves label to database node_id. Examples: - verify_node(node_label='home', userinterface_name='netflix_mobile') - verify_node(node_label='search', userinterface_name='netflix_mobile') Verification results with pass/fail status Examples: verify_node({ \"node_label\": \"home\", \"userinterface_name\": \"netflix_mobile\" })",
        "inputSchema": {
            "type": "object",
            "properties": {
                "node_label": {
                    "type": "string",
                    "description": "human readable node name like 'home', 'search'"
                },
                "userinterface_name": {
                    "type": "string",
                    "description": "user interface name for auto-resolving tree_id"
                },
                "device_id": {
                    "type": "string",
                    "description": "device identifier"
                },
                "host_name": {
                    "type": "string",
                    "description": "host name where device is connected"
                },
                "tree_id": {
                    "type": "string",
                    "description": "navigation tree ID, auto-resolved from userinterface_name if not provided"
                },
                "node_id": {
                    "type": "string",
                    "description": "exact node identifier from database, overrides node_label if provided"
                },
                "include_screenshot": {
                    "type": "boolean",
                    "description": "include a device screenshot of the verified screen in the response, default false"
                }
            },
            "required": [
                "node_label",
                "userinterface_name"
            ]
        }
    }
]
