/// <reference types="vite/client" />

declare const __APP_VERSION__: string;
declare const __APP_VERSION_RAW__: string;

interface ImportMetaEnv {
  readonly VITE_PREMIUM_FEATURES?: string;
  /** Comma-separated feature names excluded from the bundle (docs/technical/FEATURES.md). */
  readonly VITE_DISABLED_FEATURES?: string;
}

/** Generated by the `vpt-features` plugin in vite.config.ts. */
declare module 'virtual:vpt-features' {
  export const features: import('./config/features').LoadedFeature[];
}
