[supervisord]
nodaemon=true
user=vpt_user
logfile=/var/log/supervisor/supervisord.log
pidfile=/tmp/supervisord.pid
loglevel=debug
childlogdir=/var/log/supervisor

[program:flask]
command=python src/app.py
directory=/app/backend_server
user=vpt_user
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app/shared:/app/shared/src/lib:/app/backend_server/src:/app/backend_server/scripts",FLASK_ENV="production",PYTHONUNBUFFERED="1"
killasgroup=true
stopasgroup=true

[program:heatmap_processor]
command=python /app/backend_server/scripts/heatmap_processor.py
directory=/app/backend_server
user=vpt_user
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=PYTHONPATH="/app:/app/shared/lib:/app/backend_server/src:/app/backend_server/scripts",PYTHONUNBUFFERED="1"
killasgroup=true
stopasgroup=true
startsecs=30

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
