#!/usr/bin/env python3
"""Push a repo dashboard JSON (bare model, no `dashboard` wrapper) to live Grafana.
Usage: python3 _push_dashboard.py <file.json> [<file.json> ...]

Target Grafana defaults to the local instance but is overridable via env so the
same helper can push the sri/ dashboards to another Grafana:
  GRAFANA_URL=https://<grafana-host>/grafana \
  GRAFANA_USER=admin GRAFANA_PASS=<pass> \
  GRAFANA_FOLDER_UID=<uid> \
  python3 _push_dashboard.py sri/kpi-measurement.json
GRAFANA_FOLDER_UID is optional; omit it to push to the General folder.
GRAFANA_FOLDER=<folder title> resolves the uid by name (e.g. GRAFANA_FOLDER=apps).

FOLDER RULE (owner decision 2026-09-03): the per-app self-testing dashboards
(`<app>-quality.json`, generated by ../_gen_project_dashboard.py) live in the ROOT
folder `apps` (uid ffx4c203yicxsb), NOT in `VirtualPyTest`. Push them with
  GRAFANA_FOLDER=apps python3 _push_dashboard.py <app>-quality.json
Platform dashboards keep the default `VirtualPyTest` folder."""
import json, os, sys, requests, urllib3
urllib3.disable_warnings()

# The raw-IP URL returns nginx 403 since 2026-09 — the public hostname is the working default.
BASE = os.environ.get('GRAFANA_URL', 'https://virtualpytest.angelstreet.io/grafana').rstrip('/')
AUTH = (os.environ.get('GRAFANA_USER', 'admin'), os.environ['GRAFANA_PASS'])
FOLDER_UID = os.environ.get('GRAFANA_FOLDER_UID', 'dfbkqtbiuot8ga')  # VirtualPyTest (Awesomation)
FOLDER_TITLE = os.environ.get('GRAFANA_FOLDER')  # e.g. "apps" — resolved to a uid below
if FOLDER_TITLE:
    folders = requests.get(f'{BASE}/api/folders', auth=AUTH, verify=False).json()
    match = [f['uid'] for f in folders if f.get('title') == FOLDER_TITLE]
    if not match:
        sys.exit(f"folder '{FOLDER_TITLE}' not found in {BASE} (have: {[f.get('title') for f in folders]})")
    FOLDER_UID = match[0]

for path in sys.argv[1:]:
    d = json.load(open(path))
    db = d['dashboard'] if 'dashboard' in d and 'panels' in d.get('dashboard', {}) else d
    db.pop('id', None)
    db.pop('version', None)
    payload = {'dashboard': db, 'overwrite': True}
    if FOLDER_UID:
        payload['folderUid'] = FOLDER_UID
    r = requests.post(f'{BASE}/api/dashboards/db', json=payload, auth=AUTH, verify=False)
    try:
        body = r.json()
    except Exception:
        body = {'raw': r.text[:200]}
    print(f"{r.status_code}  uid={body.get('uid')}  ver={body.get('version')}  url={body.get('url')}  ({path})")
