// BLE Remote layout config — Arris STB / Universal Electronics RemoteUnit
// emulated via the bluetooth/ daemon stack.
//
// Same physical remote as the IR `stb` profile, so we reuse the same
// /stb_remote.png background image and the same button positions from
// stbRemote.ts. Key names match backend_host/src/controllers/remote/
// bluetooth/ble_conf/arris.json — keep them in sync.
//
// Buttons not yet positioned on the image but supported by the daemon
// (PLAY, PAUSE, STOP, NEXT, PREVIOUS, INFO, EXIT) — these are reachable
// via the BluetoothRemote.tsx auxiliary button strip rendered below the
// remote image.

export const bluetoothRemoteConfig = {
  remote_info: {
    name: 'BLUETOOTH',
    type: 'bluetooth_remote' as const,
    image_url: '/stb_remote.png?v=2',
    default_scale: 1,
    min_scale: 0.3,
    max_scale: 1.0,
    button_scale_factor: 4,
    global_offset: { x: 0, y: 0 },
    text_style: {
      fontSize: '32px',
      fontWeight: 'bold',
      color: 'white',
      textShadow: '2px 2px 4px rgba(0,0,0,0.9)',
    },
  },
  panel_layout: {
    collapsed: {
      width: '160px',
      height: '300px',
      position: {
        bottom: '20px',
        right: '20px',
      },
    },
    expanded: {
      width: '240px',
      height: '600px',
      position: {
        top: '100px',
        right: '20px',
      },
    },
    showScreenshotInCollapsed: false,
    showScreenshotInExpanded: true,
    header: {
      height: '40px',
      fontSize: '0.875rem',
      fontWeight: 'bold',
      iconSize: 'small',
      padding: '8px',
      backgroundColor: '#1E1E1E',
      borderColor: '#333',
      textColor: '#ffffff',
    },
  },
  remote_layout: {
    collapsed: {
      width: '120px',
      height: '240px',
      scale: 0.6,
      padding: '10px',
    },
    expanded: {
      width: '200px',
      height: '500px',
      scale: 1.0,
      padding: '25px',
    },
    background_image: {
      url: '/stb_remote.png',
      width: 200,
      height: 500,
    },
    global_offset: {
      x: 0,
      y: 0,
    },
  },
  button_layout: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 410, y: 40 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    profile: {
      key: 'PROFILE',
      label: 'P',
      position: { x: 400, y: 150 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'PROFILE',
    },
    nav_up: {
      key: 'UP',
      label: '\u25B2',
      position: { x: 262, y: 332 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '\u25C4',
      position: { x: 152, y: 432 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 262, y: 436 },
      size: { width: 28, height: 28 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '\u25BA',
      position: { x: 382, y: 432 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '\u25BC',
      position: { x: 262, y: 558 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 120, y: 632 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 268, y: 146 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    exit: {
      key: 'EXIT',
      label: '',
      position: { x: 440, y: 284 },
      size: { width: 22, height: 22 },
      shape: 'rectangle' as const,
      comment: 'Back to Live TV',
    },
    info: {
      key: 'INFO',
      label: '',
      position: { x: 440, y: 632 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: '...',
    },
    voice: {
      key: 'VOICE',
      label: '',
      position: { x: 265, y: 741 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MIC',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 406, y: 766 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 406, y: 872 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 138, y: 766 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 138, y: 872 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 114, y: 1434 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 138, y: 1008 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 276, y: 1008 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 270, y: 886 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 408, y: 1008 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 120, y: 284 },
      size: { width: 20, height: 20 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 114, y: 1138 },
      size: { width: 32, height: 26 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 258, y: 1138 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 396, y: 1138 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 114, y: 1242 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 258, y: 1242 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 396, y: 1242 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 114, y: 1336 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 258, y: 1336 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 396, y: 1336 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 258, y: 1434 },
      size: { width: 32, height: 24 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
  button_layout_recmodal: {
    power: {
      key: 'POWER',
      label: '',
      position: { x: 412, y: 44 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'POWER',
    },
    profile: {
      key: 'PROFILE',
      label: 'P',
      position: { x: 430, y: 146 },
      size: { width: 24, height: 24 },
      shape: 'circle' as const,
      comment: 'PROFILE',
    },
    nav_up: {
      key: 'UP',
      label: '\u25B2',
      position: { x: 264, y: 332 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'UP',
    },
    nav_left: {
      key: 'LEFT',
      label: '\u25C4',
      position: { x: 156, y: 434 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'LEFT',
    },
    nav_center: {
      key: 'OK',
      label: 'OK',
      position: { x: 266, y: 440 },
      size: { width: 28, height: 28 },
      shape: 'circle' as const,
      comment: 'OK',
    },
    nav_right: {
      key: 'RIGHT',
      label: '\u25BA',
      position: { x: 386, y: 434 },
      size: { width: 24, height: 28 },
      shape: 'rectangle' as const,
      comment: 'RIGHT',
    },
    nav_down: {
      key: 'DOWN',
      label: '\u25BC',
      position: { x: 264, y: 562 },
      size: { width: 28, height: 24 },
      shape: 'rectangle' as const,
      comment: 'DOWN',
    },
    back: {
      key: 'BACK',
      label: '',
      position: { x: 118, y: 636 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: 'BACK',
    },
    home: {
      key: 'HOME',
      label: '',
      position: { x: 270, y: 140 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'HOME',
    },
    exit: {
      key: 'EXIT',
      label: '',
      position: { x: 446, y: 278 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'Back to Live TV',
    },
    info: {
      key: 'INFO',
      label: '',
      position: { x: 440, y: 636 },
      size: { width: 20, height: 20 },
      shape: 'circle' as const,
      comment: '...',
    },
    voice: {
      key: 'VOICE',
      label: '',
      position: { x: 268, y: 745 },
      size: { width: 26, height: 26 },
      shape: 'circle' as const,
      comment: 'MIC',
    },
    channel_up: {
      key: 'CHANNEL_UP',
      label: '',
      position: { x: 414, y: 766 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_UP',
    },
    channel_down: {
      key: 'CHANNEL_DOWN',
      label: '',
      position: { x: 414, y: 872 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'CHANNEL_DOWN',
    },
    volume_up: {
      key: 'VOLUME_UP',
      label: '',
      position: { x: 140, y: 766 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_UP',
    },
    volume_down: {
      key: 'VOLUME_DOWN',
      label: '',
      position: { x: 140, y: 872 },
      size: { width: 22, height: 26 },
      shape: 'rectangle' as const,
      comment: 'VOLUME_DOWN',
    },
    mute: {
      key: 'MUTE',
      label: '',
      position: { x: 120, y: 1446 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'MUTE',
    },
    rewind: {
      key: 'REWIND',
      label: '',
      position: { x: 140, y: 1013 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'REWIND',
    },
    play_pause: {
      key: 'PLAY_PAUSE',
      label: '',
      position: { x: 275, y: 1013 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'PLAY_PAUSE',
    },
    rec: {
      key: 'RECORD',
      label: '',
      position: { x: 275, y: 894 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'RECORD',
    },
    fast_forward: {
      key: 'FORWARD',
      label: '',
      position: { x: 412, y: 1013 },
      size: { width: 22, height: 22 },
      shape: 'circle' as const,
      comment: 'FORWARD',
    },
    tv_guide: {
      key: 'TVGUIDE',
      label: '',
      position: { x: 120, y: 278 },
      size: { width: 18, height: 18 },
      shape: 'rectangle' as const,
      comment: 'TVGUIDE',
    },
    number_1: {
      key: 'KEY_1',
      label: '',
      position: { x: 120, y: 1142 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_1',
    },
    number_2: {
      key: 'KEY_2',
      label: '',
      position: { x: 260, y: 1142 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_2',
    },
    number_3: {
      key: 'KEY_3',
      label: '',
      position: { x: 404, y: 1142 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_3',
    },
    number_4: {
      key: 'KEY_4',
      label: '',
      position: { x: 120, y: 1242 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_4',
    },
    number_5: {
      key: 'KEY_5',
      label: '',
      position: { x: 260, y: 1242 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_5',
    },
    number_6: {
      key: 'KEY_6',
      label: '',
      position: { x: 404, y: 1242 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_6',
    },
    number_7: {
      key: 'KEY_7',
      label: '',
      position: { x: 120, y: 1346 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_7',
    },
    number_8: {
      key: 'KEY_8',
      label: '',
      position: { x: 260, y: 1346 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_8',
    },
    number_9: {
      key: 'KEY_9',
      label: '',
      position: { x: 404, y: 1346 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_9',
    },
    number_0: {
      key: 'KEY_0',
      label: '',
      position: { x: 260, y: 1446 },
      size: { width: 30, height: 22 },
      shape: 'rectangle' as const,
      comment: 'KEY_0',
    },
  },
} as const;

export type BluetoothRemoteConfig = typeof bluetoothRemoteConfig;

// DEV-ONLY: the remote panel is memoized on props that don't include this
// config, so editing button positions won't repaint via HMR. Force a full
// reload on save while tuning the layout. Remove before committing.
if (import.meta.hot) {
  import.meta.hot.accept(() => window.location.reload());
}
